CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR NOT NULL PRIMARY KEY,
    PWHASH VARCHAR
);

MERGE INTO USERS (USERNAME, PWHASH) VALUES ('anonymous', 'THIS_IS_IGNORED');

CREATE TABLE IF NOT EXISTS BOOKMARKS (
    URL VARCHAR NOT NULL,
    TITLE VARCHAR,
    NOTES VARCHAR,
    IMAGEURL VARCHAR,
    TAGS VARCHAR,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    LASTVISITED TIMESTAMP,
    VISITCOUNT BIGINT,
    USERNAME VARCHAR NOT NULL,
    PRIMARY KEY (URL, USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAGS (
    TAGNAME VARCHAR NOT NULL,
    COLOR VARCHAR,
    USERNAME VARCHAR NOT NULL,
    PRIMARY KEY (TAGNAME, USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

/*
CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
CALL FTL_INIT();
CALL FTL_CREATE_INDEX('PUBLIC', 'BOOKMARKS', 'TITLE,NOTES,CONTENT') where not exists(select * from UESRS where UESRNAME = "anonymous");
*/
